micronaut:
  application:
    name: fundamentos
  router:
    static-resources:
      default:
        paths: classpath:public
        mapping: /**
  http:
    services:
      status-invest:
        url: https://statusinvest.com.br
        read-timeout: 30s

jpa:
  default:
    reactive: true
    entity-scan:
      packages: 'com.moselli.fundamentos.entity'
    properties:
      hibernate:
        show-sql: true
        hbm2ddl:
          auto: update
        connection:
          url: jdbc:postgresql://localhost:5432/postgres
          username: postgres
          password: 'postgres'
          db-type: postgres

endpoints:
  loggers:
    enabled: true
  beans:
    enabled: true
  routes:
    enabled: true
  health:
    enabled: true
    details-visible: ANONYMOUS
  info:
    enabled: true