micronaut:
  application:
    name: fundamentos
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/fundamentos
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages: 'com.moselli.fundamentos.entity'
    properties:
      hibernate.hbm2ddl.auto: update
router:
    static-resources:
      main:
        paths: classpath:views
        mapping: /views/**  